name: EmberZNet Zigbee firmware build

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ezsp-firmware-build.yaml
  workflow_run:
    workflows:
      - "Silicon Labs build container image"
    branches:
      - main
    types:
      - completed

jobs:
  ezsp-firmware-build:
    strategy:
      matrix:
        include:
          - firmware: ncp-uart-hw-yellow
            device: MGM210PA32JIA
            with: simple_led:board_activity
            patchpath: "EmberZNet/Yellow"
            sdk_version: "4.1.4"
            ezsp_version: "7.1.4.0"
          - firmware: ncp-uart-hw-skyconnect
            device: EFR32MG21A020F512IM32
            patchpath: "EmberZNet/SkyConnect"
            sdk_version: "4.1.4"
            ezsp_version: "7.1.4.0"
    uses: ./.github/workflows/silabs-firmware-build.yaml
    with:
      firmware: ${{ matrix.firmware }}
      device: ${{ matrix.device }}
      with: ${{ matrix.with }}
      patchpath: ${{ matrix.patchpath }}
      sdk_version: ${{ matrix.sdk_version }}
      ezsp_version: ${{ matrix.ezsp_version }}