name: EmberZNet Zigbee firmware build

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ezsp-firmware-build.yaml
  workflow_run:
    workflows:
      - "Silicon Labs build container image"
    branches:
      - main
    types:
      - completed

jobs:
  ezsp-firmware-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nabucasa/silabs-firmware-builder
    strategy:
      matrix:
        include:
          - firmware: ncp-uart-hw-yellow
            with: MGM210PA32JIA,simple_led:board_activity
            patchpath: "EmberZNet/Yellow"
          - firmware: ncp-uart-hw-skyconnect
            with: EFR32MG21A020F512IM32
            patchpath: "EmberZNet/SkyConnect"
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Generate Firmware Project
        run: |
          slc generate \
              --with="${{ matrix.with }}" \
              --project-file=/gecko_sdk/protocol/zigbee/app/ncp/sample-app/ncp-uart-hw/ncp-uart-hw.slcp \
              --export-destination=${{ matrix.firmware }} \
              --copy-proj-sources --new-project --force \
              --configuration=" \
                SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE:64, \
                EMBER_APS_UNICAST_MESSAGE_COUNT:20, \
                EMBER_NEIGHBOR_TABLE_SIZE:26, \
                EMBER_SOURCE_ROUTE_TABLE_SIZE:200, \
                "
      - name: Patch Firmware
        run: |
          cd ${{ matrix.firmware }}
          patch -p1 < ../${{ matrix.patchpath }}/*.patch

      - name: Build Firmware
        run: |
          cd ${{ matrix.firmware }}
          make -f ncp-uart-hw.Makefile
      - uses: actions/upload-artifact@v3
        with:
          name: ezsp-firmware
          path: /build/${{ matrix.firmware }}
